env: dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  rabbitmq:
    host: 192.168.56.131
    port: 5672
    username: guest
    password: guest
server:
  port: 8092
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.imooc.sellproduct.model
  jpa:
    show-sql: true

