env: dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  rabbitmq:
    host: 192.168.42.131
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
server:
  port: 8091
