env: dev
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8092
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.imooc.sellproduct.model
  jpa:
    show-sql: true

