env: dev
server:
  port: 8091
girl: 
  name: lili
  age: 19
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.imooc.sellproduct.model
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

